enquete/agenda/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from agenda import views

from django.views.generic import RedirectView
app_name = 'agenda'
urlpatterns = [
    
    path('', views.index, name='index'),
    


    path('admin/', admin.site.urls),
    path('tarefas/todos/',views.list_todos_tarefas),


    path('tarefas/usuario/', views.list_user_tarefas),
    path('tarefas/detalhes/<slug:id>/', views.tarefa_detalhes),
    path('tarefas/registro/', views.cadastrar_tarefa),
    path('tarefas/registro/submit', views.set_tarefa),
    path('tarefas/delete/<slug:id>/', views.delete_tarefa),

    path('login/',views.login_usuario),
    
    path('login/registro',views.cadastrar_usuario),
    path('login/submit',views.submit),
    path('logout/',views.logout_usuario),

    path('submit', RedirectView.as_view(url='tarefas/todos/'))



]

enquete/enquete/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views
from django.views.generic import RedirectView


urlpatterns = [
    path('', include('main.urls')),
    path('agenda/', include('agenda.urls')),
    path('admin/', admin.site.urls),
]

enquete/main/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from main import views
app_name = 'main'
urlpatterns = [

    path('', views.root, name='root'),
    
    # path('', RedirectView.as_view(url='tarefas/todos/')),

    path('enquete',
        views.IndexView.as_view(), name='index'
        ),
 


    path('enquete/<int:pk>',
        views.DetalhesView.as_view(), name ='detalhes'
    ),
    path('enquete/<int:pk>/resultado',
        views.ResultadoView.as_view(), name ='resultado'
    ),
    path('enquete/<int:id_enquete>/votacao',
        views.votacao, name ='votacao'
    ),
]

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime

class Usuario(models.Model):
  login = models.CharField(max_length = 50)
  senha = models.CharField(max_length = 50)
  email = models.CharField(max_length = 100)
  def __str__(self):
      return self.login

class Categoria(models.Model):
    titulo = models.CharField(max_length = 200)
    descricao = models.TextField()
    data_de_criacao = models.DateTimeField('Data de Criação')
    def __str__(self):
        return self.titulo

class Pergunta(models.Model):
    texto = models.CharField(max_length = 200)
    data_publicacao = models.DateTimeField('Data de Publicação')
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE,
        default = None,
        null =True
    )
    usuario = models.ForeignKey(
        Usuario,
        on_delete=models.CASCADE,
        default = None,
        null =True
    )
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return  agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora
    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'ultimas 24hs?'

class Opcao(models.Model):
    texto = models.CharField(max_length = 200)
    votos = models.IntegerField(default = 0)
    pergunta= models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Pergunta, Opcao, Categoria


# Create your views here.

def home(request):
   # categorias = 'teste'
    categorias = Categoria.objects.all()
    pergunta_list = Pergunta.objects.all()
    return render(request, 'main/pergunta_list.html', {'categorias': categorias, 'pergunta_list':pergunta_list})

# alteração aqui
def root(request):
    return render(request, 'main/root.html', {})

#enqueteView
class IndexView(generic.ListView):

    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()
            ).order_by('-data_publicacao')[:5]

#enqueteView
# class Enquete2View(generic.ListView):

#     def get_queryset(self):
#         return Pergunta.objects.filter(
#             data_publicacao__lte=timezone.now()
#             ).order_by('-data_publicacao')[:5]
# ate aqui




class DetalhesView(generic.DetailView):
    model = Pergunta
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte = timezone.now())


class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'



def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'main/detalhes.html', {
            'pergunta': pergunta,
            'error_message': "Selecione uma opcão VÁLIDA!"
            })
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(
            reverse('main:resultado', args=(pergunta.id,))
            )

enquete/main/templates/main/pergunta_detail.html
<html>
    <head>
        <title>App Enquete</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>

    <body>
        <h2> Detalhes da Enquete {{ pergunta.id }}</h2>
        <u> Pergunta</u>:{{pergunta.texto}}<br/>
        <u>Data de Publicação</u>:{{pergunta.data_publicacao}}

        {% if error_message %}
            <hr/>
                <strong>{{ error_message }}</strong>
            <hr/>
        {% endif %}
        <form action ="{% url 'main:votacao' pergunta.id%}" method = "post">

            {% csrf_token %}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li><input type= "radio" name = "opcao"
                        id ="opcao{{forloop.counter}}" value ="{{opcao.id}}">
                        <label for="opcao{{ forloop.counter}}">
                            {{opcao.texto}}
                        </label>
                    </li>
                {% endfor %}
            </ul>
            <input style="background-color:green; color: white;" type="submit" value="Registre o seu Voto">
        </form>
    </body>
</html>

enquete/main/templates/main/pergunta_list.html
<!--função pra carregar arquivos static de estilo (load)-->
{%load static %}
<html>
<head>
    <title>App Enquete</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" type="text/css" href="{%static 'main/style.css' %}">
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">-->
</head>
<body>
    {% if pergunta_list %}
        <h2>Lista das Ultimas Enquetes</h2>
        <ul class="t">
            {% for pergunta in pergunta_list %}
                <li><a href="{% url 'main:detalhes' pergunta.id %}">
                    {{ pergunta.texto }}
                </a> (<a href="{% url 'main:resultado' pergunta.id %}">ver parcial</a>)</li>
            {% endfor %}
        </ul>

    {% else %}
        <h3>Não há enquetes cadastrados até o nomento!</h3>
    {% endif %}
    <div class="dropdown">
        <label for="nome">Lista de Categorias:</label><br>
        <select id="categoria" name="categoria" required>
          <option hidden value="">Categorias</option>
          {% for categoria in categorias%}s
              <option value="{{ categoria.id }}">{{categoria.titulo}}</option>
            {% endfor %}
        </select>



    <button type="button"  onclick="location.href='/'">Consultar</button>



    </div>



</body>

</html>

enquete/main/templates/main/resultado.html
<html>
    <head>
        <title>App Enquete</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <body>
        <h2>Resultado Parcial da Enquete {{pergunta.id}}</h2>
        <u> Pergunta</u>:{{pergunta.texto}}<br/>
        <u>Data de Publicação</u>: {{pergunta.data_publicacao}}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li>{{opcao.texto}} = {{opcao.votos}}
                    voto{{opcao.votos | pluralize}}</li>
                {% endfor %}
            </ul>
            <hr/>
            <a href = "{% url 'main:detalhes' pergunta.id %}">Deseja votar Novamente?</a>
            <br/>
            <a href = "{% url 'main:index' %}">Retornar á pagina Principal</a>
            <br>
            <a href = "{% url 'main:root' %}">Retornar á pagina root</a>

        </body>
</html>

enquete/main/templates/main/root.html
<html>

    <head>
        <title> Aplicação DSWeb 2020.1</title>
    </head>
    <body>
        <h1>Aplicação da Disciplina DSWeb 2020.1</h1>
        <h3>Selecione a aplicação desejada:</h3>
        <ul>
            <li><a href="{% url 'main:index' %}">Aplicação Enquete - Modulo 01</a></li>

            <!--linha importante-->
            <li><a href="{% url 'agenda:index' %}">Aplicação Agenda de Tarefas - Modulo 02</a></li>

        </ul>
        <hr>
        <b>Rafael Rufino </b> (<i>rafaelrafael.52@gmail.com</i>)

    </body>

</html>